name: My CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up openJDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Build with Gradle
        run: make build
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          # Set CC_TEST_REPORTER_ID as secret of your repo
          CC_TEST_REPORTER_ID: ${{secrets.CODE_CLIMATE_ID}}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
        with:
          # The report file must be there, otherwise Code Climate won't find it
          # coverageCommand: make test
          coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
